@startuml banda

Instrumento <|-- Guitarra
Instrumento <|-- Saxo
Instrumento <|-- Tiple
Instrumento <|-- Piano
Instrumento <|-- Bongos
Instrumento <|-- Maracas
Instrumento <|-- Trompeta
Instrumento <|-- Violin
Instrumento <|-- Clarinete
Instrumento <|-- Triangulo

Musico *-- Instrumento
Banda *-- Instrumento

Instrumento : afinar()
Instrumento : tocar()

Musico : instrumento
Musico : tocar_instrumento()
Musico : afinar_instrumento()

Banda : musicos
Banda : afinar()
Banda : tocar()
Banda : arma_banda()

Guitarra : afinar()
Guitarra : tocar()

@enduml